using IncomeMeter.Api.Models;
using Microsoft.Extensions.Options;

namespace IncomeMeter.Api.Services.Storage;

/// <summary>
/// Stores files on the local disk. Suitable for development and single-instance deployments.
/// </summary>
public class LocalFileStorageService : IFileStorageService
{
    private readonly string _root;

    public LocalFileStorageService(IOptions<StorageSettings> settings, IWebHostEnvironment env)
    {
        var path = settings.Value.LocalPath;
        _root = Path.GetFullPath(Path.IsPathRooted(path) ? path : Path.Combine(env.ContentRootPath, path));
        Directory.CreateDirectory(_root);
    }

    private string Resolve(string storageKey)
    {
        // Keys are generated by us, but guard against path traversal anyway.
        var full = Path.GetFullPath(Path.Combine(_root, storageKey.Replace('/', Path.DirectorySeparatorChar)));
        if (!full.StartsWith(_root, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Invalid storage key");
        return full;
    }

    public async Task<string> SaveAsync(string storageKey, Stream content, string contentType, CancellationToken ct = default)
    {
        var full = Resolve(storageKey);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        await using var fs = new FileStream(full, FileMode.Create, FileAccess.Write, FileShare.None, 81920, useAsync: true);
        await content.CopyToAsync(fs, ct);
        return storageKey;
    }

    public Task<Stream?> OpenReadAsync(string storageKey, CancellationToken ct = default)
    {
        var full = Resolve(storageKey);
        if (!File.Exists(full)) return Task.FromResult<Stream?>(null);
        Stream s = new FileStream(full, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true);
        return Task.FromResult<Stream?>(s);
    }

    public Task DeleteAsync(string storageKey, CancellationToken ct = default)
    {
        var full = Resolve(storageKey);
        if (File.Exists(full)) File.Delete(full);
        return Task.CompletedTask;
    }
}
